### PR TITLE
Remove old device registration on the new registration

### PR DESCRIPTION
**Pull request by janantala**
Fixes Issue #52

### CODE REVIEW

**Comment by dmoranj** [comment]
I've downloaded your branch and there are some linter errors in the code. Please, before commiting to the repository, execute the "grunt" command without parameters, in order to check that both the tests and syntax rules work as expected.

**Comment by janantala** [comment]
@dmoranj Lint errors are fixed, but your tests are failing.

**Comment by dmoranj** [comment]
I've downloaded your branch and the tests seem to work for me. What tests are failing and what's the error? There is one test that must be put into quarantine: the one named: "When the user invokes the Cancel operation on a resource should stop sending updates for the resource value" as it randomly fails sometimes. If that's the one test that is failing, I'll merge the request and work on stabilizing the test in other issue.

**Comment by janantala** [comment]
No test runs correctly for me, but it is the same as in telefonicaid:develop branch (git clone and clean npm install) so you can merge this request. Do you have a public CI server like codeship or travis?

There is a log:

```
❯ grunt
Running "jshint:gruntfile" (jshint) task
>> 1 file lint free.

Running "jshint:lib" (jshint) task
>> 21 files lint free.

Running "jshint:test" (jshint) task
>> 15 files lint free.

Running "mochaTest:unit" (mochaTest) task


  Client-side device management
    When a Write request arrives to the client
      1) should change the appropriate value in the selected object
    When a Read request arrives to the client for an existent resource of an existent object
      2) should send a response with the required object value
    When a Read request arrives to the client for an unexistent object instance
      3) should raise a 4.04 OBJECT_NOT_FOUND error
    When a Read request arrives to the client for an unexistent resource of an object
      4) should raise a 4.04 RESOURCE_NOT_FOUND error
    When a Discover request arrives targeting an existent Object ID
      5) should return all the instances of the selected Object ID
    When a Discover request arrives targeting an existent Object instance ID
      6) should return all the resources of the selected Object instance ID
    When a Discover request arrives targeting an unexistent resource ID
      - should raise a RESOURCE_NOT_FOUND error
    When a Discover request arrives targeting an unexistent object type ID
      - should raise a OBJECT_NOT_FOUND error
    When a Discover request arrives targeting an unexistent object instance ID
      - should raise a OBJECT_NOT_FOUND error
    When a Write attributes request arrives targeting an existent resource ID
      7) should overwrite the given attributes in the selected resource ID
    When a Write attributes request arrives targeting an existent object type ID
      8) should overwrite the given attributes in the selected object type ID
    When a Write attributes request arrives targeting an existent object instance ID
      9) should overwrite the given attributes in the selected object instance ID
    When a Write attributes request arrives targeting an unexistent resource ID
      - should raise a RESOURCE_NOT_FOUND error
    When a Write attributes request arrives targeting an unexistent object ID
      - should raise a OBJECT_NOT_FOUND error
    When a Execute request arrives to the client
      10) should call the execution handler for the selected object

  Client-side information management
    When a Read requests arrives to the client with the Observe Option for value changes
      11) should call the read handler once with the original value
      12) should return the current value of the selected object
      13) should update the value each time there is a new value
      14) should only send updates for the selected resource
    When two observers are created for resources of the same object and one of them is updated
      15) should create two different observers, one for each resource
      16) should call only the handler of the updated resource
    When the client cancels an observed value
      17) should cease sending messages to the remote server
    When a Read requests arrives to the client with an Maximum Period attribute of 100ms
      18) "before each" hook

  0 passing (1s)
  5 pending
  18 failing

  1) Client-side device management When a Write request arrives to the client should change the appropriate value in the selected object:
     Uncaught AssertionError: expected {
  code: '4.04',
  message: 'The device with id: 20 was not found',
  name: 'DEVICE_NOT_FOUND'
} to not exist
      at /Users/janantala/Downloads/lwm2m-node-lib/test/unit/client/client-device-managment-test.js:98:28
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:544:30
      at getObject (/Users/janantala/Downloads/lwm2m-node-lib/lib/services/server/inMemoryDeviceRegistry.js:79:9)
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:656:23
      at fn (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:641:34)
      at Object._onImmediate (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:557:34)
      at processImmediate [as _immediateCallback] (timers.js:345:15)

  2) Client-side device management When a Read request arrives to the client for an existent resource of an existent object should send a response with the required object value:
     Uncaught AssertionError: expected {
  code: '4.04',
  message: 'The device with id: 21 was not found',
  name: 'DEVICE_NOT_FOUND'
} to not exist
      at /Users/janantala/Downloads/lwm2m-node-lib/test/unit/client/client-device-managment-test.js:135:28
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:544:30
      at getObject (/Users/janantala/Downloads/lwm2m-node-lib/lib/services/server/inMemoryDeviceRegistry.js:79:9)
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:656:23
      at fn (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:641:34)
      at Object._onImmediate (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:557:34)
      at processImmediate [as _immediateCallback] (timers.js:345:15)

  3) Client-side device management When a Read request arrives to the client for an unexistent object instance should raise a 4.04 OBJECT_NOT_FOUND error:
      
      actual expected
      
      "OBJECT_NOT_FOUNDDEVICE_NOT_FOUND"
      
      at Assertion.fail (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/should/lib/assertion.js:113:17)
      at Assertion.prop.(anonymous function) (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/should/lib/assertion.js:39:14)
      at /Users/janantala/Downloads/lwm2m-node-lib/test/unit/client/client-device-managment-test.js:170:35
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:544:30
      at getObject (/Users/janantala/Downloads/lwm2m-node-lib/lib/services/server/inMemoryDeviceRegistry.js:79:9)
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:656:23
      at fn (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:641:34)
      at Object._onImmediate (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:557:34)
      at processImmediate [as _immediateCallback] (timers.js:345:15)

  4) Client-side device management When a Read request arrives to the client for an unexistent resource of an object should raise a 4.04 RESOURCE_NOT_FOUND error:
      
      actual expected
      
      "RESOURCE_NOT_FOUNDDEVICE_NOT_FOUND"
      
      at Assertion.fail (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/should/lib/assertion.js:113:17)
      at Assertion.prop.(anonymous function) (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/should/lib/assertion.js:39:14)
      at /Users/janantala/Downloads/lwm2m-node-lib/test/unit/client/client-device-managment-test.js:202:35
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:544:30
      at getObject (/Users/janantala/Downloads/lwm2m-node-lib/lib/services/server/inMemoryDeviceRegistry.js:79:9)
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:656:23
      at fn (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:641:34)
      at Object._onImmediate (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:557:34)
      at processImmediate [as _immediateCallback] (timers.js:345:15)

  5) Client-side device management When a Discover request arrives targeting an existent Object ID should return all the instances of the selected Object ID:
     Uncaught AssertionError: expected {
  code: '4.04',
  message: 'The device with id: 24 was not found',
  name: 'DEVICE_NOT_FOUND'
} to not exist
      at /Users/janantala/Downloads/lwm2m-node-lib/test/unit/client/client-device-managment-test.js:226:28
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:544:30
      at getObject (/Users/janantala/Downloads/lwm2m-node-lib/lib/services/server/inMemoryDeviceRegistry.js:79:9)
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:656:23
      at fn (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:641:34)
      at Object._onImmediate (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:557:34)
      at processImmediate [as _immediateCallback] (timers.js:345:15)

  6) Client-side device management When a Discover request arrives targeting an existent Object instance ID should return all the resources of the selected Object instance ID:
     Uncaught AssertionError: expected {
  code: '4.04',
  message: 'The device with id: 25 was not found',
  name: 'DEVICE_NOT_FOUND'
} to not exist
      at /Users/janantala/Downloads/lwm2m-node-lib/test/unit/client/client-device-managment-test.js:251:28
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:544:30
      at getObject (/Users/janantala/Downloads/lwm2m-node-lib/lib/services/server/inMemoryDeviceRegistry.js:79:9)
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:656:23
      at fn (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:641:34)
      at Object._onImmediate (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:557:34)
      at processImmediate [as _immediateCallback] (timers.js:345:15)

  7) Client-side device management When a Write attributes request arrives targeting an existent resource ID should overwrite the given attributes in the selected resource ID:
     Uncaught AssertionError: expected {
  code: '4.04',
  message: 'The device with id: 26 was not found',
  name: 'DEVICE_NOT_FOUND'
} to not exist
      at /Users/janantala/Downloads/lwm2m-node-lib/test/unit/client/client-device-managment-test.js:299:32
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:544:30
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:254:17
      at done (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:129:15)
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:32:16
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:251:21
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:575:34
      at getObject (/Users/janantala/Downloads/lwm2m-node-lib/lib/services/server/inMemoryDeviceRegistry.js:79:9)
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:656:23
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:570:21

  8) Client-side device management When a Write attributes request arrives targeting an existent object type ID should overwrite the given attributes in the selected object type ID:
     Uncaught AssertionError: expected {
  code: '4.04',
  message: 'The device with id: 27 was not found',
  name: 'DEVICE_NOT_FOUND'
} to not exist
      at /Users/janantala/Downloads/lwm2m-node-lib/test/unit/client/client-device-managment-test.js:342:32
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:544:30
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:254:17
      at done (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:129:15)
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:32:16
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:251:21
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:575:34
      at getObject (/Users/janantala/Downloads/lwm2m-node-lib/lib/services/server/inMemoryDeviceRegistry.js:79:9)
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:656:23
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:570:21

  9) Client-side device management When a Write attributes request arrives targeting an existent object instance ID should overwrite the given attributes in the selected object instance ID:
     Uncaught AssertionError: expected {
  code: '4.04',
  message: 'The device with id: 28 was not found',
  name: 'DEVICE_NOT_FOUND'
} to not exist
      at /Users/janantala/Downloads/lwm2m-node-lib/test/unit/client/client-device-managment-test.js:385:32
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:544:30
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:254:17
      at done (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:129:15)
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:32:16
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:251:21
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:575:34
      at getObject (/Users/janantala/Downloads/lwm2m-node-lib/lib/services/server/inMemoryDeviceRegistry.js:79:9)
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:656:23
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:570:21

  10) Client-side device management When a Execute request arrives to the client should call the execution handler for the selected object:
     Uncaught AssertionError: expected {
  code: '4.04',
  message: 'The device with id: 29 was not found',
  name: 'DEVICE_NOT_FOUND'
} to not exist
      at /Users/janantala/Downloads/lwm2m-node-lib/test/unit/client/client-device-managment-test.js:428:28
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:544:30
      at getObject (/Users/janantala/Downloads/lwm2m-node-lib/lib/services/server/inMemoryDeviceRegistry.js:79:9)
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:656:23
      at fn (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:641:34)
      at Object._onImmediate (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:557:34)
      at processImmediate [as _immediateCallback] (timers.js:345:15)

  11) Client-side information management When a Read requests arrives to the client with the Observe Option for value changes should call the read handler once with the original value:
     Uncaught AssertionError: expected {
  code: '4.04',
  message: 'The device with id: 30 was not found',
  name: 'DEVICE_NOT_FOUND'
} to not exist
      at /Users/janantala/Downloads/lwm2m-node-lib/test/unit/client/client-information-management-test.js:106:28
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:544:30
      at getObject (/Users/janantala/Downloads/lwm2m-node-lib/lib/services/server/inMemoryDeviceRegistry.js:79:9)
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:656:23
      at fn (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:641:34)
      at Object._onImmediate (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:557:34)
      at processImmediate [as _immediateCallback] (timers.js:345:15)

  12) Client-side information management When a Read requests arrives to the client with the Observe Option for value changes should return the current value of the selected object:
     Uncaught AssertionError: expected {
  code: '4.04',
  message: 'The device with id: 31 was not found',
  name: 'DEVICE_NOT_FOUND'
} to not exist
      at /Users/janantala/Downloads/lwm2m-node-lib/test/unit/client/client-information-management-test.js:121:28
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:544:30
      at getObject (/Users/janantala/Downloads/lwm2m-node-lib/lib/services/server/inMemoryDeviceRegistry.js:79:9)
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:656:23
      at fn (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:641:34)
      at Object._onImmediate (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:557:34)
      at processImmediate [as _immediateCallback] (timers.js:345:15)

  13) Client-side information management When a Read requests arrives to the client with the Observe Option for value changes should update the value each time there is a new value:
     Uncaught AssertionError: expected {
  code: '4.04',
  message: 'The device with id: 32 was not found',
  name: 'DEVICE_NOT_FOUND'
} to not exist
      at /Users/janantala/Downloads/lwm2m-node-lib/test/unit/client/client-information-management-test.js:141:28
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:544:30
      at getObject (/Users/janantala/Downloads/lwm2m-node-lib/lib/services/server/inMemoryDeviceRegistry.js:79:9)
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:656:23
      at fn (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:641:34)
      at Object._onImmediate (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:557:34)
      at processImmediate [as _immediateCallback] (timers.js:345:15)

  14) Client-side information management When a Read requests arrives to the client with the Observe Option for value changes should only send updates for the selected resource:
     Uncaught AssertionError: expected {
  code: '4.04',
  message: 'The device with id: 33 was not found',
  name: 'DEVICE_NOT_FOUND'
} to not exist
      at /Users/janantala/Downloads/lwm2m-node-lib/test/unit/client/client-information-management-test.js:171:28
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:544:30
      at getObject (/Users/janantala/Downloads/lwm2m-node-lib/lib/services/server/inMemoryDeviceRegistry.js:79:9)
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:656:23
      at fn (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:641:34)
      at Object._onImmediate (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:557:34)
      at processImmediate [as _immediateCallback] (timers.js:345:15)

  15) Client-side information management When two observers are created for resources of the same object and one of them is updated should create two different observers, one for each resource:
      
      actual expected
      
      20
      
      at Assertion.fail (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/should/lib/assertion.js:113:17)
      at Assertion.prop.(anonymous function) (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/should/lib/assertion.js:39:14)
      at /Users/janantala/Downloads/lwm2m-node-lib/test/unit/client/client-information-management-test.js:226:52
      at Object.listObservers (/Users/janantala/Downloads/lwm2m-node-lib/lib/services/client/read.js:337:5)
      at /Users/janantala/Downloads/lwm2m-node-lib/test/unit/client/client-information-management-test.js:225:33
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:544:30
      at getObject (/Users/janantala/Downloads/lwm2m-node-lib/lib/services/server/inMemoryDeviceRegistry.js:79:9)
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:656:23
      at fn (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:641:34)
      at Object._onImmediate (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:557:34)

  16) Client-side information management When two observers are created for resources of the same object and one of them is updated should call only the handler of the updated resource:
      
      actual expected
      
      30
      
      at Assertion.fail (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/should/lib/assertion.js:113:17)
      at Assertion.prop.(anonymous function) (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/should/lib/assertion.js:39:14)
      at null._onTimeout (/Users/janantala/Downloads/lwm2m-node-lib/test/unit/client/client-information-management-test.js:262:49)
      at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

  17) Client-side information management When the client cancels an observed value should cease sending messages to the remote server:
     Uncaught AssertionError: expected {
  code: '4.04',
  message: 'The device with id: 36 was not found',
  name: 'DEVICE_NOT_FOUND'
} to not exist
      at /Users/janantala/Downloads/lwm2m-node-lib/test/unit/client/client-information-management-test.js:301:28
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:544:30
      at getObject (/Users/janantala/Downloads/lwm2m-node-lib/lib/services/server/inMemoryDeviceRegistry.js:79:9)
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:656:23
      at fn (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:641:34)
      at Object._onImmediate (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:557:34)
      at processImmediate [as _immediateCallback] (timers.js:345:15)

  18) Client-side information management When a Read requests arrives to the client with an Maximum Period attribute of 100ms "before each" hook:
     Error: done() invoked with non-Error: [object Object]
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/mocha/lib/runnable.js:196:38
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:254:17
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:151:21
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:251:21
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:615:34
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:544:30
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:254:17
      at done (/Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:129:15)
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:32:16
      at /Users/janantala/Downloads/lwm2m-node-lib/node_modules/async/lib/async.js:251:21



Warning: Task "mochaTest:unit" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by dmoranj** [comment]
Mmmm that's problematic. What Node.js version are you using? I'll add the project to travis ASAP to avoid this environment-specific problems, as it is really important to check past functionality is not broken with new patches. I'll make some checks and merge your PR.

**Comment by janantala** [comment]
It is a problem of node module when `should.not.exist()` is not recognized. Maybe I have an another version in my environment config... And there are also missing done callbacks for pending tests.

**Comment by dmoranj** [comment]
`done()` callbacks for pending tests? They shouldn't be needed, AFAIK, can you elaborate on that?

Maybe there are `should` requirements missing, and only working on my environment. We will check that with Travis.

**Comment by dmoranj** [comment]
LGTM. I'll be working on the Travis task tomorrow in order to solve the environment problems.

**Comment by janantala** [comment]
I found out that this problem happens when the lwm2m server is already running. Otherwise there is only that one "Cancel operation" test failing. I will add some features.

**Pull request merged**
