### PR TITLE
Set device type from query parameter in registration url

### PR DESCRIPTION
**Pull request by versatildefuy**
Hi,

the functionality introduced is described in #152 . Due to test errors in lightweightm2m-node-lib discovered in https://github.com/telefonicaid/lightweightm2m-iotagent/pull/210#discussion_r338207022 I have created more tests and adapted the functionality to ensure tests pass in both repositories. 

I hope it works this time :)

### CODE REVIEW

**Comment by fgalan** [comment]
Comparing this PR and PR #152 apart form tests and the change in .gitignore both seem to be exactly equal. Is that correct or maybe I have missed some change?

If the contribution is the same, the problem with PR #152 should appear again... Have you tested this branch with lightwigthm2m-agent (it's a matter of modifying package.json in the agent to point to this PRs branch in the lwm2m-node-lib dependency and run the tests with that)?

**Comment by versatildefuy** [comment]
Changes are in commits b6e11ed74fd67e104a598754ae7935b3e16e5e60 and fc91b8f3261b0f5eaf06ccdcc7debb4a0edb1528 . Yes, I pass all tests in lightwigthm2m-agent repo before creating this PR. 

In any case, this introduces an interesting question. If you have to pass lightwigthm2m-agent tests every time you perform a change in this repository you don't have two repositories: one with an lwm2m library and other acting as iotagent; you have a single repository split in two. Making harder the testing and development process. 

This is only my point of view and I am not proposing anything but it seems, in this case, the consumer, lightwigthm2m-agent component, is directing the development of the provider, lwm2m-node-lib.

**Comment by fgalan** [comment]
> In any case, this introduces an interesting question. If you have to pass lightwigthm2m-agent tests every time you perform a change in this repository you don't have two repositories: one with an lwm2m library and other acting as iotagent; you have a single repository split in two. Making harder the testing and development process.
>
> This is only my point of view and I am not proposing anything but it seems, in this case, the consumer, lightwigthm2m-agent component, is directing the development of the provider, lwm2m-node-lib.

Originally, the lwm2m library was designed with the idea of be independent of the IOTA (so it could be reused in theory in other developments) but at the end this is probably not happening and the coupling is high. Maybe we should change this, but is would be a big change so we would need to think about it with care...

Thanks for the feedback!

**Comment by fgalan** [comment]
A trivial conflict has happended in CHANGES_NEXT_RELEASE. Please solve so we can have a new look to the PR.

**Pull request merged**
