### PR TITLE
Add support for objects 1/2

### PR DESCRIPTION
**Pull request by muoren**
Currently this library lacks support to stream `LWM2M Objects` as defined by OMA LWM2M Spec. This is a prerequisite PR that adds library support to transport LWM2M Object instances.

We add an LWM2M Object `Schema` constructor to:

* Specify Object _definitions_ with Resource names, IDs, type and whether is mandatory or not.
* Validate Object Instances and Resources

This PR adds also support to JSON de/serializer (application/vnd.oma.lwm2m+json media type).
Added too unit tests for all the new features.

Here is an example:

```js

var lwm2m = require('lwm2m-node-lib');
var Schema = lwm2m.Schema;

// this can be found in lwm2m.objects.security
var schema = new Schema('LWM2M Security', {
  uri:        { type: String, id: 0, required: true },
  serverId:   { type: Number, id: 10, required: true },
  bootstrap:  { type: Boolean, id: 1, required: true },
  clientCert: { type: Buffer, id: 3, required: true },
  secret:     { type: Buffer, id: 5, required: true },
  // etc.
});

// keys can be both named, from the schema, or directly resource IDs
var obj = {
  uri: 'coap://localhost:5683', // or 0 : 'coap://localhost:5683'
  bootstrap: false,
  serverId: 2,
  clientCert: fs.readFileSync('./cert.pem'),
  secret: fs.readFileSync('./key.pem')
};

// JSON
// senml library is not exported, since it is meant to be used by read/write APIs
try {
  var payload = senml.serialize(obj, schema);
  var obj2 = senml.parse(payload, schema);
  assert.deepEqual(obj, obj2);
catch (e) {
  // ...
}
```

New APIs for reading/writing objects are not part of this PR, and no API has been modified, other than exporting the Schema constructor and some LWM2M Object definitions.

A contrived example of how this could be used to read/write objects:
```js
var schema = require('./MySchema');
var options = { schema: schema };

// if no schema is passed in the options, return the unparsed payload to the user
read(ep, path, options, callback); 

options = { 
  schema: schema,
  writeFormat: 'application-vnd-oma-lwm2m/json' 
}

write(ep, path, obj, options, callback);
```
Any input is appreciated. The patch is purposely limited in functionality (and intrusiveness) to discuss further on the implementation details.

### CODE REVIEW

**Comment by muoren** [comment]
Any input is appreciated. The patch is purposely limited in functionality (and intrusiveness) to discuss further on the implementation details.

**Comment by mrutid** [comment]
Hi @muoren, first of all thanks for your contribution. @dmoranj will no longer maintain this repository, and our hability to make code reviews on this repo will be very limited for a while.

On the other hand, we have an administrative problem. We forgot to add the Contribution Policy to this repo like in: 
     https://github.com/telefonicaid/iotagent-json/blob/master/ContributionPolicy.txt
It's not intended to cover small contributions, but big ones. Your PR it's big&great! but we must retain the IPR of all the files on all our repos (it's a mess to have mixed IPRs in one product). You may retain the authorship of your modules, that's perfect to us (Adding "Author" to the license header) but 
- * Copyright 2017 Alexandre Moreno <alex_moreno@tutk.com>
 must be 
+ * Copyright 2017 Telefonica Investigación y Desarrollo, S.A.U
(there is no need to sign anything if you don't want to).

If you feel confortable with this scenario it will be a pleasure to make the merge. Sorry for the inconveniences and thanks again for you contribution.

**Comment by muoren** [comment]
Hi @mrutid,

Nice and thanks for your reply.

> code reviews on this repo will be very limited for a while.

If the project goes unmaintained then would be appropriate to mention that somewhere explicitly, if that is the case. Otherwise I will be happy to contribute further.

> we must retain the IPR of all the files on all our repos

Not a problem. I will transfer the copyright of my contributions to your company.

**Comment by mrutid** [comment]
Thanks for your understanding.

Surely this is a timey wimey wibbly wobbly temporal situation, and this repo will have a maintainer soon.

Your request looks good to me. Nice job.

**Pull request merged**
