### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by AlvaroVega**

### CODE REVIEW

**Comment by fgalan** [comment]
LGTM

Passing the ball to @dcalvoalonso for final LGTM before merging

**Comment by dcalvoalonso** [comment]
Just one comment, following what we have done with the rest of repositories, shall we remove https://github.com/telefonicaid/lwm2m-node-lib/blob/master/npm-shrinkwrap.json before merging this?

**Comment by fgalan** [comment]
Sounds good to me. In fact, I thougth it was already removed :)

**Comment by fgalan** [comment]
@dcalvoalonso npm-shrinkwrap.json has been deleted

**Comment by dcalvoalonso** [comment]
LGTM

**Pull request merged**
